name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        push: true
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: kareemadamu/dockerizednodeapp:latest

    - name: 'Wait for SSH'
      run: |
        while ! nc -w5 -z ${{ secrets.INSTANCE_IP }} 22; do
                sleep 5
                echo "SSH not available..."
        done; echo "SSH ready!"
    - name: 'SSH to VM'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: opc
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        timeout: 30s
        script: |
          docker run -p 8080:8080 -d kareemadamu/dockerizednodeapp 
